// ignore_for_file: constant_identifier_names

// ====================
// GENERAL / LOCAL
// ====================

const int UNEXPECTED_STATUS_CODE = -1;
const String UNEXPECTED_ERROR_CODE = "UNEXPECTED_ERROR";

const int OFFLINE_STATUS_CODE = -2;
const String OFFLINE_ERROR_CODE = "NO_INTERNET_CONNECTION";

const int DATA_PARSING_STATUS_CODE = -3;
const String DATA_PARSING_ERROR_CODE = "DATA_PARSING_ERROR";

const int PROCESS_TIMEOUT_STATUS_CODE = -4;
const String PROCESS_TIMEOUT_ERROR_CODE = "PROCESS_TIMEOUT";

// ====================
// DIO ERROR CODE / NETWORK
// ====================

const String API_CONNECTION_TIMEOUT_ERROR_CODE = 'DIO_CONNECTION_TIMEOUT';
const String API_SEND_TIMEOUT_ERROR_CODE = 'DIO_SEND_TIMEOUT';
const String API_RECEIVE_TIMEOUT_ERROR_CODE = 'DIO_RECEIVE_TIMEOUT';
const String API_BAD_CERTIFICATE_ERROR_CODE = 'DIO_BAD_CERTIFICATE_ERROR';
const String API_BAD_RESPONSE_ERROR_CODE = 'DIO_BAD_RESPONSE_ERROR';
const String API_BAD_REQUEST_ERROR_CODE = 'HTTP_400_BAD_REQUEST';
const String API_UNAUTHORIZED_ERROR_CODE = 'HTTP_401_UNAUTHORIZED';
const String API_FORBIDDEN_ERROR_CODE = 'HTTP_403_FORBIDDEN';
const String API_NOT_FOUND_ERROR_CODE = 'HTTP_404_NOT_FOUND';
const String API_CONFLICT_ERROR_CODE = 'HTTP_409_CONFLICT';
const String API_UNPROCESSABLE_ERROR_CODE = 'HTTP_422_UNPROCESSABLE';
const String API_TOO_MANY_REQUESTS_ERROR_CODE = 'HTTP_429_TOO_MANY_REQUESTS';
const String API_SERVER_ERROR_CODE = 'HTTP_5XX_SERVER_ERROR';
const String API_SERVICE_UNAVAILABLE_ERROR_CODE = 'HTTP_503_SERVICE_UNAVAILABLE';
const String API_CANCEL_REQUEST_ERROR_CODE = 'DIO_CANCEL_REQUEST';
const String API_CONNECTION_ERROR_CODE = 'DIO_CONNECTION_ERROR';
const String API_UNKNOWN_ERROR_CODE = 'DIO_UNKNOWN_ERROR_CODE';

// ====================
// PERMISSION
// ====================

const String PERMISSION_DENIED_ERROR_CODE = 'PERMISSION_DENIED';
const String PERMISSION_PERMANENTLY_DENIED_ERROR_CODE = 'PERMISSION_PERMANENTLY_DENIED';

// ====================
// LOCATION
// ====================

const String LOCATION_SERVICE_DISABLED_ERROR_CODE = 'LOCATION_SERVICE_DISABLED';
const String LOCATION_PERMISSION_DENIED_ERROR_CODE = 'LOCATION_PERMISSION_DENIED';
const String LOCATION_PERMISSION_DENIED_FOREVER_ERROR_CODE = 'LOCATION_PERMISSION_DENIED_FOREVER';
